# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@1.3.0
#  browser-tools: circleci/browser-tools@1.4.0

executors:
  openjdk11:
    docker:
      - image: cimg/openjdk:11.0
      
jobs:
  run-maven:
    executor: openjdk11
    steps:
      - maven/test:
         app_src_directory: selenium-cucumber

# jobs:
#   install-browser-tools:
#     docker:
#       - image: 'cimg/node:13.12-browsers'
#     steps:
#       - browser-tools/install-chrome
#       - browser-tools/install-chromedriver

workflows:
  maven_test:
    jobs:
      - run-maven

#       - install-browser-tools
#      - maven/test:
#          app_src_directory: selenium-cucumber
