version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  build:
    working_directory: ~/repo/selenium-cucumber
    docker:
      - image: cimg/openjdk:11.0.16-browsers
    steps:
      - checkout:
          path: ~/repo
      - browser-tools/install-browser-tools
      - run:
          name: Install Dependencies
          command: mvn test
          environment:
            CHROME_DRIVER_PATH: /usr/local/bin/chromedriver
     - store_artifacts:
          path: ~/repo/selenium-cucumber/cucumberHtmlReport.html

workflows:
  sample:
    jobs:
      - build
