# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@1.3.0
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  test:
    executor: browser-tools/default
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

workflows:
  maven_test:
    jobs:
      - test
      - maven/test:
          app_src_directory: selenium-cucumber
