version: 2.1

jobs:
  build:
    working_directory: ~/repo/selenium-cucumber
    docker:
      - image: cimg/openjdk:11.0.16-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout:
          path: ~/repo
      - run:
          name: Install Dependencies
          command: mvn test
          environment:
            CHROME_DRIVER_PATH: /usr/lib

workflows:
  sample:
    jobs:
      - build
