version: 2.1

jobs:
  build:
    working_directory: ~/repo/selenium-cucumber
    docker:
      - image: cimg/openjdk:11.0.16-browsers
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Dependencies
          command: mvn test

workflows:
  sample:
    jobs:
      - build
